<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ini</string>
		<string>INI</string>
		<string>inf</string>
		<string>INF</string>
		<string>dec</string>
		<string>DEC</string>
		<string>dsc</string>
		<string>DSC</string>	
		<string>fdf</string>
		<string>FDF</string>					
	</array>
	<key>name</key>
	<string>DSC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.dsc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(#|;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semi-colon.dsc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.dsc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.dsc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.dsc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\[)(.*?)(\])\s*</string>
			<key>name</key>
			<string>meta.tag.section.dsc</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.property.dsc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.quote.dsc</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.name.dsc</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.quote.dsc</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.equals.dsc</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.value.dsc</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.quote.dsc</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.name.value.dsc</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.quote.dsc</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*(["']?)(.+?)(\2)\s*(=))?\s*((["']?)(.*?)(\7))\s*$\n?</string>
			<key>name</key>
			<string>meta.declaration.dsc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dsc</string>
	<key>uuid</key>
	<string>0d7afab0-3e2d-11e2-a498-047d7b5f9057</string>
</dict>
</plist>
